apiVersion: apps/v1
kind: Deployment
metadata:
  name: promexporter
spec:
  selector:
    matchLabels:
      app: promexporter
  replicas: 1
  template:
    metadata:
      labels:
        app: promexporter
    spec:
      containers:
        - name: promexporter
          image: 'nginx/nginx-prometheus-exporter:0.10.0'
          args:
            - '-nginx.scrape-uri=http://nginx:8080/metrics'
          ports:
            - containerPort: 9113

