apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-metrics-config
data:
  metrics.conf: |
    server {
      listen      8080;
      server_name localhost;

      location /metrics {
        stub_status;
      }
    }

